// Generated by CoffeeScript 1.4.0
(function() {

  exports.languages = function() {
    return {
      '.coffee': {
        name: 'coffee-script',
        symbol: '#'
      },
      '.js': {
        name: 'javascript',
        symbol: '//',
        multi_start: '/*',
        multi_end: '*/'
      },
      '.rb': {
        name: 'ruby',
        symbol: '#'
      },
      '.py': {
        name: 'python',
        symbol: '#'
      },
      '.java': {
        name: 'java',
        symbol: '//',
        multi_start: '/*',
        multi_end: '*/'
      },
      '.pp': {
        name: 'ruby',
        symbol: '#',
        multi_start: '/*',
        multi_end: '*/'
      },
      '.conf': {
        name: 'bash',
        symbol: '#'
      },
      '.c': {
        name: 'c',
        symbol: '//',
        multi_start: '/*',
        multi_end: '*/'
      },
      '.clj': {
        name: 'clojure',
        symbol: ';',
        multi_start: '(comment',
        multi_end: ')'
      },
      '.bf': {
        name: 'brainfuck',
        symbol: '#'
      },
      '.php': {
        name: 'php',
        symbol: '//',
        multi_start: '/*',
        multi_end: '*/'
      }
    };
  };

}).call(this);
