// Generated by CoffeeScript 1.4.0
(function() {
  var assert, parser;

  assert = require('assert');

  parser = require('../src/docco.coffee');

  suite('Playah', function() {
    return print('asd');
  });

}).call(this);
