// Generated by CoffeeScript 1.4.0
(function() {
  var assert;

  assert = require('assert');

  describe('Array', function() {
    return describe('#indexOf()', function() {
      it('Should return -1 when item is not found in Array', function() {
        assert.equal(-1, [1, 2, 3].indexOf(0));
        return assert.equal(-1, [1, 2, 3].indexOf(-1));
      });
      return it('Should return the index of the array where the item. This should always be greater than -1', function() {
        assert.equal(0, [-1, 0, 1].indexOf(-1));
        assert.equal(1, [-1, 0, 1].indexOf(0));
        return assert.equal(2, [-1, 0, 1].indexOf(1));
      });
    });
  });

  suite('Some Test Suite', function() {
    test('Something should be equal because I say so', function() {
      return assert.equal(1, 1);
    });
    test('Something should be true because I want it that way', function() {
      return assert.ok(1 === 1);
    });
    return suite('Some nested test suite', function() {
      return test('Something else', function() {
        return assert.ok(true);
      });
    });
  });

}).call(this);
